
window.onload = function() {
    const useNodeJS = false;   // if you are not using a node server, set this value to false
    const defaultLiffId = "1656445468-pPVkELw7";   // change the default LIFF value if you are not using a node server

    // DO NOT CHANGE THIS
    let myLiffId = "";

    // if node is used, fetch the environment variable and pass it to the LIFF method
    // otherwise, pass defaultLiffId
    if (useNodeJS) {
        fetch('/send-id')
            .then(function(reqResponse) {
                return reqResponse.json();
            })
            .then(function(jsonResponse) {
                myLiffId = jsonResponse.id;
                initializeLiffOrDie(myLiffId);
            })
            .catch(function(error) {
                //document.getElementById("liffAppContent").classList.add('hidden');
               // document.getElementById("nodeLiffIdErrorMessage").classList.remove('hidden');
            });
    } else {
        myLiffId = defaultLiffId;
        initializeLiffOrDie(myLiffId);

    }
};

/**
* Check if myLiffId is null. If null do not initiate liff.
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiffOrDie(myLiffId) {
    if (myLiffId) {       
        initializeLiff(myLiffId);
    }
}

/**
* Initialize LIFF
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiff(myLiffId) {
    liff.init({
            liffId: myLiffId
        })
        .then(() => {
            // start to use LIFF's api
            initializeApp();
        })
        .catch((err) => {
           // document.getElementById('lblUserId').textContent = err.error;
            //document.getElementById("liffAppContent").classList.add('hidden');
            //document.getElementById("liffInitErrorMessage").classList.remove('hidden');
        });
}

/**
 * Initialize the app by calling functions handling individual app components
 */
function initializeApp() {
    displayLiffData();
    
    
    if (liff.isLoggedIn()) {
        
        liff.getProfile().then(profile => {
            const userName = profile.displayName;
            const userId = profile.userId;
            
            if (document.getElementById('txtLineId'))
                document.getElementById('txtLineId').value = userId;

            if (document.getElementById('lblUserId')) {
                document.getElementById('lblUserId').textContent = userId;
                document.getElementById('lblUserName').textContent = userName;
                document.getElementById('txtDisplay').value = userName;
            }


            /*
            liff.sendMessages([
                {
                  type: 'text',
                  text: 'TEST Register!'
                }
              ])
                .then(() => {
                    
                })
                .catch((err) => {
                  console.log('error', err);
                  document.getElementById('txtDisplay').value = err;
                });
            
                */
             
            /*

               liff.sendMessages([
                {
                  type: 'text',
                  text: 'Hello, World!'
                }
              ])
                .then(() => {
                    liff.closeWindow();
                })
                .catch((err) => {
                  console.log('error', err);
                  document.getElementById('txtDisplay').value = err;
                });
            //timePost("");
           // checkRegister(userId,"00001");
           liff.sendMessages([
            {
                type:'text',
                text: 'test from liff'                
            },
            {
                type:'text',
                text: getCurrentTime()
            }

            ])
            .then(() => {
                console.log('message sent');
              

            })
            .catch((err) => {
                alert(err);
                console.log('error', err);
            });
            */
        })
        .catch((err) => {
            console.log('error', err);
        });
    
    }
    //liff.getProfile().userId;

}

/**
* Display data generated by invoking LIFF methods
*/
function displayLiffData() {
    
    if (document.getElementById('browserLanguage')) {
        document.getElementById('browserLanguage').textContent = liff.getLanguage();
        document.getElementById('sdkVersion').textContent = liff.getVersion();
        document.getElementById('lineVersion').textContent = liff.getLineVersion();
        document.getElementById('deviceOS').textContent = liff.getOS();
    }
}

/**
* Alert the user if LIFF is opened in an external browser and unavailable buttons are tapped
*/

/**
* Toggle access token data field
*/
function toggleAccessToken() {
    toggleElement('accessTokenData');
}

/**
* Toggle profile info field
*/
function toggleProfileData() {
    toggleElement('profileInfo');
}

/**
* Toggle scanCode result field
*/
function toggleQrCodeReader() {
    toggleElement('scanQr');
}

/**
* Toggle specified element
* @param {string} elementId The ID of the selected element
*/
function toggleElement(elementId) {
    const elem = document.getElementById(elementId);
    if (elem.offsetWidth > 0 && elem.offsetHeight > 0) {
        elem.style.display = 'none';
    } else {
        elem.style.display = 'block';
    }
}

